language: scala
scala:
  - 2.12.2

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_install:
    - cd docker
    - docker-compose up -d
    - cd ..

script:
    - sbt scalafmt::test
    - sbt test:scalafmt::test
    - sbt test
    - sbt assembly
    - ./submitToDockerizedSpark.sh
